import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('train.csv')
print("First 5 rows:")
print(df.head())
print("\nShape of dataset:", df.shape)
print("\nData Types and Null Info:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
df.drop(columns=['Cabin'], inplace=True)
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})
df.drop(columns=['Name', 'Ticket', 'PassengerId'], inplace=True)
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
sns.countplot(x='Survived', hue='Sex', data=df)
plt.title("Survival Count by Gender")
plt.show()
sns.countplot(x='Survived', hue='Pclass', data=df)
plt.title("Survival Count by Passenger Class")
plt.show()
sns.histplot(df['Age'], kde=True, bins=10)
plt.title("Age Distribution")
plt.show()
sns.histplot(df['Fare'], kde=True, bins=10)
plt.title("Fare Distribution")
plt.show()

